import "../globals.css";
import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import AppCardProvider from "@/components/Shop/CardProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const inter = League_Spartan({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Custom Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppCardProvider
        >
          <Header />
          {children}
          <Footer />
        </AppCardProvider>
      </body>
    </html>
  );
}
