name: "CD: (Continuos Delivery): Main Worlflow"

env: 
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: 
  push:
    branches: [main]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies 
        run: yarn install
      - name: Run lint
        run: yarn lint --fix
      - name: Run test 
        run: yarn test
      - name: Run Deploy
        run: yarn deploy:prod